trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    displayName: 'Run Hello World Script'
    steps:
    - script: echo "Hello, world!""
      displayName: 'Print Hello World'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Run Deploy script'
    steps:
    - script: echo "Deployiny"
      displayName: 'Print Deploying'  
